name: human-fall-detection
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip

  # code-checks
  - pre-commit>=2.15
  - pytest>=7.4

  # framework
  - pytorch::pytorch>=2.1
  - pytorch::torchvision>=0.16
  - pandas>=2.1
  - openpyxl>=3.0

  - pip:
      # code-checks
      - ruff>=0.1

      # framework
      - openmim>=0.3

      # tools
      - jupyter>=1.0
      - ipympl>=0.9
      - pandas-stubs>=2.1
