name: human-fall-detection
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip

  # code-checks
  - mypy=1.5.1
  - pre-commit>=2.15.0

  # framework
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0

  - pip:
      # code-checks
      - ruff>=0.1.3

      # framework
      - openmim>=0.3.9
